# Generated by Django 5.0.3 on 2026-03-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='hls_dir',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='lecture',
            name='hls_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='hls_manifest',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='lecture',
            name='hls_status',
            field=models.CharField(choices=[('none', 'None'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', max_length=16),
        ),
    ]
